# -*- coding: utf-8 -*-
"""MIMIC-IV ICU time-series extraction, translated from TimeDiff.

Reference: TimeDiff `preprocess/mimic4_everything.ipynb` (the vital/lab
extraction is shared with `mimic4_time_irregular_icd.ipynb`, the ICD matrix with
`preprocess/mimic4_save_icd.py`).  The reference reads a local PostgreSQL MIMIC-IV
through `helpers.DataBaseLoader`, querying the `mimiciv_derived.vitalsign`,
`mimiciv_derived.chemistry`, `mimiciv_derived.antibiotic`, `mimiciv_hosp.admissions`
and `mimiciv_hosp.patients` tables.

This module reproduces that preprocessing from the PhysioNet CSV distribution
instead, so no database is required.  The three `mimiciv_derived` tables are not
part of the CSV download, so they are rebuilt here from `icu/chartevents.csv`,
`hosp/labevents.csv` and `hosp/prescriptions.csv` following the MIT-LCP concept
definitions they are generated by (`mimic-iv/concepts/measurement/vitalsign.sql`,
`.../chemistry.sql`, `mimic-iv/concepts/medication/antibiotic.sql`).

Pipeline (each step matches the reference):

1. Pivot chartevents into one row per (subject_id, stay_id, charttime) with the
   five vitals TimeDiff uses, averaging duplicate itemids at one charttime.
2. Pivot labevents into one row per specimen with glucose / creatinine / sodium.
3. Keep ICU stays with >= 70 charted values of every vital; labs only need one.
4. Resample each signal onto an hourly grid and keep the first 72 hours.  Each
   signal contributes a value channel and a missing-value mask channel.
5. Append four non-temporal channels.  Age and mortality are held constant over
   the 72 slots; the ICD and antibiotic channels instead abuse the 72 slots to
   carry a 72-long binary indicator over the most frequent codes/drugs, which is
   what the reference does.
6. Split 75/25 stratified on mortality and save .npy tensors.

Outputs, written to `--out-dir` (default `processed_mimic/`):

* `train.npy` / `test.npy` -- float32 `(n_stays, 20, 72)`, one row per ICU stay,
  75% / 25% of the cohort.  Axis 1 is the channel, axis 2 is hours 0..71.  Each
  signal is windowed from its own first observation rather than from a clock
  shared by the stay, so the channels of one row are not mutually aligned in
  absolute time; the reference resamples each series independently likewise.
  Channels, in order:
      0..9   vitals as value/mask pairs: heart_rate, sbp, dbp, resp_rate, spo2
      10..15 labs as value/mask pairs: glucose, creatinine, sodium
      16     icd        binary over the 72 most frequent ICD codes
      17     antibiotic binary over the 72 most frequent antibiotics
      18     age        anchor_age, repeated across all 72 hours
      19     mortality  hospital_expire_flag, repeated across all 72 hours
  Value channels hold NaN where nothing was measured on that hour; the mask
  channel next to each is 1 exactly there and 0 where a value is present.  A
  signal never observed for a stay is an all-NaN channel with an all-ones mask,
  which is why the lab channels are mostly masked.  Indices 16 and 17 are
  indexed by code rank, not by hour; 18 and 19 are constant along axis 2.
  `channel_names()` returns these 20 names in order.
* `stays_train.npy` / `stays_test.npy` -- int64 `(n_stays,)`, the MIMIC-IV
  `stay_id` of each row of the corresponding tensor, in the same order.  Rows
  are shuffled by the split, so these are needed to join back to MIMIC.
* `channels.json` -- the channel names, cohort sizes and the settings used.
* `annotations.json` -- per-stay status labels for the same cohort, keyed by
  `stay_id`, with a `fields` block describing each one and `label_rates` giving
  the positive rate of every binary label.  Nothing here feeds the tensors; it
  is the outcome and diagnosis metadata the CSV release carries, collected so
  the stays can be conditioned on or evaluated against more than the single
  in-hospital mortality bit in channel 20.  Covers mortality (in-hospital, in-ICU,
  30-day and 1-year from `patients.dod`, which also catches the ~26k deaths that
  happen after discharge), discharge destination, 30-day readmission, length of
  stay, care unit, service line, APR-DRG severity and risk of mortality, and the
  admission's ICD codes with the primary one resolved to its title.

Deliberate departures from the reference, which cannot be reproduced exactly:

* Lab timestamps are rounded to 20 minutes and then de-duplicated.  The
  reference keeps whichever row Postgres returned first, which is unordered;
  here the earliest original timestamp wins.
* A subject whose antibiotics all fall outside the top 72 gets a zero channel.
  The reference appends no channel at all and so silently drops the stay.
* ICD codes are ranked by raw `icd_code`; the reference re-inserts an ICD-9
  decimal point first, which changes the label but not the ranking.
* Tensor channel 20 is the reference's subject-level mortality: it is 1 when the
  subject died in *any* admission, not necessarily the one being modelled.
  `annotations.json` carries the admission-level flag under the same name, and
  the two disagree for a few percent of stays; the annotation is the correct one.

Usage:
    python mimic.py --csv-dir physionet.org/files/mimiciv/3.1 --out-dir processed_mimic
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
import pandas as pd

LOG = logging.getLogger("mimic")

MIMIC_TIME_FORMAT = "%Y-%m-%d %H:%M:%S"

# (itemids, low, high, high_is_inclusive) per concepts/measurement/vitalsign.sql
VITAL_ITEMS: dict[str, tuple[tuple[int, ...], float, float, bool]] = {
    "heart_rate": ((220045,), 0, 300, False),
    "sbp": ((220179, 220050, 225309), 0, 400, False),
    "dbp": ((220180, 220051, 225310), 0, 300, False),
    "resp_rate": ((220210, 224690), 0, 70, False),
    "spo2": ((220277,), 0, 100, True),
}
VITALS: tuple[str, ...] = tuple(VITAL_ITEMS)
_VITAL_ITEMIDS = frozenset(i for ids, *_ in VITAL_ITEMS.values() for i in ids)

# (itemid, high) per concepts/measurement/chemistry.sql; all also require > 0
LAB_ITEMS: dict[str, tuple[int, float]] = {
    "glucose": (50931, 10000),
    "creatinine": (50912, 150),
    "sodium": (50983, 200),
}
LABS: tuple[str, ...] = tuple(LAB_ITEMS)
_LAB_ITEMIDS = frozenset(itemid for itemid, _ in LAB_ITEMS.values())

# channel order of the saved tensor: value/mask per signal, then the statics
SIGNALS: tuple[str, ...] = VITALS + LABS
STATIC_CHANNELS: tuple[str, ...] = ("icd", "antibiotic", "age", "mortality")

N_STEPS = 72  # hours kept per stay; also the width of the ICD/antibiotic vectors
_HOUR_NS = 3_600_000_000_000

# drug-name and route rules of concepts/medication/antibiotic.sql
_ANTIBIOTIC_SUBSTRINGS = (
    "adoxa", "ala-tet", "alodox", "amikacin", "amikin", "amoxicill", "amphotericin",
    "anidulafungin", "ancef", "clavulanate", "ampicillin", "augmentin", "avelox",
    "avidoxy", "azactam", "azithromycin", "aztreonam", "axetil", "bactocill",
    "bactrim", "bactroban", "bethkis", "biaxin", "bicillin l-a", "cayston",
    "cefazolin", "cedax", "cefoxitin", "ceftazidime", "cefaclor", "cefadroxil",
    "cefdinir", "cefditoren", "cefepime", "cefotan", "cefotetan", "cefotaxime",
    "ceftaroline", "cefpodoxime", "cefpirome", "cefprozil", "ceftibuten", "ceftin",
    "ceftriaxone", "cefuroxime", "cephalexin", "cephalothin", "cephapririn",
    "chloramphenicol", "cipro", "ciprofloxacin", "claforan", "clarithromycin",
    "cleocin", "clindamycin", "cubicin", "dicloxacillin", "dirithromycin", "doryx",
    "doxycy", "duricef", "dynacin", "ery-tab", "eryped", "eryc", "erythrocin",
    "erythromycin", "factive", "flagyl", "fortaz", "furadantin", "garamycin",
    "gentamicin", "kanamycin", "keflex", "kefzol", "ketek", "levaquin",
    "levofloxacin", "lincocin", "linezolid", "macrobid", "macrodantin", "maxipime",
    "mefoxin", "metronidazole", "meropenem", "methicillin", "minocin",
    "minocycline", "monodox", "monurol", "morgidox", "moxatag", "moxifloxacin",
    "mupirocin", "myrac", "nafcillin", "neomycin", "nicazel doxy 30",
    "nitrofurantoin", "norfloxacin", "noroxin", "ocudox", "ofloxacin", "omnicef",
    "oracea", "oraxyl", "oxacillin", "pc pen vk", "pce dispertab", "panixine",
    "pediazole", "penicillin", "periostat", "pfizerpen", "piperacillin",
    "tazobactam", "primsol", "proquin", "raniclor", "rifadin", "rifampin",
    "rocephin", "smz-tmp", "septra", "septra ds", "solodyn", "spectracef",
    "streptomycin", "sulfadiazine", "sulfamethoxazole", "trimethoprim", "sulfatrim",
    "sulfisoxazole", "suprax", "synercid", "tazicef", "tetracycline", "timentin",
    "tobramycin", "unasyn", "vancocin", "vancomycin", "vantin", "vibativ",
    "vibra-tabs", "vibramycin", "zinacef", "zithromax", "zosyn", "zyvox",
)
_ANTIBIOTIC_PATTERN = "|".join(re.escape(s) for s in _ANTIBIOTIC_SUBSTRINGS)
_EXCLUDED_ROUTES = frozenset({"OU", "OS", "OD", "AU", "AS", "AD", "TP"})


class _GroupReducer:
    """Streaming groupby for data that does not fit in memory at raw row level.

    Partial aggregates are appended per chunk and re-reduced once they grow past
    ``max_rows``, so a group split across chunk boundaries still reduces exactly.
    """

    def __init__(self, keys: Sequence[str], how: str, max_rows: int = 12_000_000):
        self.keys = list(keys)
        self.how = how
        self.max_rows = max_rows
        self._parts: list[pd.DataFrame] = []
        self._rows = 0

    def add(self, frame: pd.DataFrame) -> None:
        if frame.empty:
            return
        self._parts.append(frame)
        self._rows += len(frame)
        if self._rows > self.max_rows:
            self._reduce()

    def _reduce(self) -> None:
        if len(self._parts) == 1 and self._rows <= self.max_rows:
            return
        merged = pd.concat(self._parts, ignore_index=True, copy=False)
        merged = merged.groupby(self.keys, sort=False, as_index=False).agg(self.how)
        self._parts = [merged]
        self._rows = len(merged)

    def result(self) -> pd.DataFrame:
        if not self._parts:
            return pd.DataFrame(columns=self.keys)
        self._reduce()
        return self._parts[0]


def _to_datetime(series: pd.Series) -> pd.Series:
    return pd.to_datetime(series, format=MIMIC_TIME_FORMAT, errors="coerce")


def _read_chunks(
    path: Path,
    usecols: Sequence[str],
    dtype: dict[str, str],
    chunksize: int,
    nrows: int | None = None,
) -> Iterable[pd.DataFrame]:
    reader = pd.read_csv(
        path,
        usecols=list(usecols),
        dtype=dtype,
        chunksize=chunksize,
        nrows=nrows,
    )
    for i, chunk in enumerate(reader, start=1):
        if i % 20 == 0:
            LOG.info("  %s: %s chunks read", path.name, f"{i:,}")
        yield chunk


def load_vitalsign(
    csv_dir: Path, chunksize: int = 2_000_000, nrows: int | None = None
) -> pd.DataFrame:
    """Rebuild ``mimiciv_derived.vitalsign`` from ``icu/chartevents.csv``.

    One row per (subject_id, stay_id, charttime); itemids mapping to the same
    concept are averaged, out-of-range values dropped before averaging.
    """
    path = csv_dir / "icu" / "chartevents.csv"
    LOG.info("vitalsign: scanning %s", path)
    sum_cols = [f"{v}_sum" for v in VITALS]
    n_cols = [f"{v}_n" for v in VITALS]
    keys = ["subject_id", "stay_id", "charttime"]
    reducer = _GroupReducer(keys, how="sum")

    for chunk in _read_chunks(
        path,
        usecols=["subject_id", "stay_id", "charttime", "itemid", "valuenum"],
        dtype={
            "subject_id": "int64",
            "stay_id": "float64",
            "itemid": "int32",
            "valuenum": "float32",
            "charttime": "string",
        },
        chunksize=chunksize,
        nrows=nrows,
    ):
        chunk = chunk[chunk["stay_id"].notna() & chunk["itemid"].isin(_VITAL_ITEMIDS)]
        if chunk.empty:
            continue
        chunk = chunk.assign(
            stay_id=chunk["stay_id"].astype("int64"),
            charttime=_to_datetime(chunk["charttime"]),
        )
        values = {}
        for name, (ids, low, high, inclusive) in VITAL_ITEMS.items():
            keep = chunk["itemid"].isin(ids) & (chunk["valuenum"] > low)
            keep &= chunk["valuenum"] <= high if inclusive else chunk["valuenum"] < high
            values[name] = chunk["valuenum"].where(keep)
        tidy = chunk[keys].assign(**values)
        grouped = tidy.groupby(keys, sort=False)[list(VITALS)]
        partial = pd.concat(
            [
                grouped.sum().set_axis(sum_cols, axis=1),
                grouped.count().set_axis(n_cols, axis=1),
            ],
            axis=1,
        ).reset_index()
        reducer.add(partial)

    agg = reducer.result()
    if agg.empty:
        return pd.DataFrame(columns=keys + list(VITALS))
    counts = agg[n_cols].to_numpy()
    sums = agg[sum_cols].to_numpy(dtype="float64")
    means = np.divide(sums, counts, out=np.full_like(sums, np.nan), where=counts > 0)
    out = agg[keys].copy()
    out[list(VITALS)] = means.astype("float32")
    out = out.sort_values(["stay_id", "charttime"], ignore_index=True)
    LOG.info("vitalsign: %s rows, %s stays", f"{len(out):,}", f"{out.stay_id.nunique():,}")
    return out


def load_chemistry(
    csv_dir: Path, chunksize: int = 4_000_000, nrows: int | None = None
) -> pd.DataFrame:
    """Rebuild the ``mimiciv_derived.chemistry`` columns TimeDiff uses.

    One row per specimen_id, as in concepts/measurement/chemistry.sql.  The
    reference only reads glucose, creatinine and sodium out of that table.
    """
    path = csv_dir / "hosp" / "labevents.csv"
    LOG.info("chemistry: scanning %s", path)
    keys = ["specimen_id"]
    carried = ["subject_id", "hadm_id", "charttime"]
    reducer = _GroupReducer(keys, how="max")

    for chunk in _read_chunks(
        path,
        usecols=["subject_id", "hadm_id", "specimen_id", "itemid", "charttime", "valuenum"],
        dtype={
            "subject_id": "int64",
            "hadm_id": "float64",
            "specimen_id": "int64",
            "itemid": "int32",
            "valuenum": "float32",
            "charttime": "string",
        },
        chunksize=chunksize,
        nrows=nrows,
    ):
        chunk = chunk[chunk["itemid"].isin(_LAB_ITEMIDS) & chunk["valuenum"].notna()]
        chunk = chunk[chunk["valuenum"] > 0]
        if chunk.empty:
            continue
        chunk = chunk.assign(charttime=_to_datetime(chunk["charttime"]))
        values = {}
        for name, (itemid, high) in LAB_ITEMS.items():
            keep = (chunk["itemid"] == itemid) & (chunk["valuenum"] <= high)
            values[name] = chunk["valuenum"].where(keep)
        tidy = chunk[keys + carried].assign(**values)
        partial = tidy.groupby(keys, sort=False, as_index=False).max()
        reducer.add(partial)

    agg = reducer.result()
    if agg.empty:
        return pd.DataFrame(columns=["subject_id", "charttime"] + list(LABS))
    out = agg[["subject_id", "charttime"] + list(LABS)].copy()
    out[list(LABS)] = out[list(LABS)].astype("float32")
    out = out.sort_values(["subject_id", "charttime"], ignore_index=True)
    LOG.info(
        "chemistry: %s specimens, %s subjects", f"{len(out):,}", f"{out.subject_id.nunique():,}"
    )
    return out


def select_stays(vitals: pd.DataFrame, min_measurements: int = 70) -> np.ndarray:
    """ICU stays with at least ``min_measurements`` charted values of every vital.

    The reference counts each vital separately with its own ``num >= 70`` filter
    and then intersects the five stay_id sets.
    """
    counts = vitals.groupby("stay_id")[list(VITALS)].count()
    eligible = counts.index[(counts >= min_measurements).all(axis=1)].to_numpy()
    for name in VITALS:
        LOG.info("  %s: %s stays >= %s values", name, f"{(counts[name] >= min_measurements).sum():,}", min_measurements)
    LOG.info("select_stays: %s stays in all five", f"{len(eligible):,}")
    return np.sort(eligible)


def _hourly_window(
    times: pd.DatetimeIndex,
    values: np.ndarray,
    round_to: str | None = None,
    n_steps: int = N_STEPS,
) -> np.ndarray | None:
    """First ``n_steps`` hours of ``values`` on an hourly grid, or None if too short.

    Equivalent to the reference's ``resample('H').asfreq()`` followed by a
    ``len(temp) >= n_steps`` test: the grid runs from the first to the last
    observation floored to the hour, and ``asfreq`` keeps only observations
    landing exactly on a grid point, so off-the-hour readings become missing.
    """
    if len(times) == 0:
        return None
    if round_to is not None:
        times = times.round(round_to)
    stamps = times.asi8
    order = np.argsort(stamps, kind="stable")
    stamps, values = stamps[order], np.asarray(values, dtype="float64")[order]
    unique = np.ones(len(stamps), dtype=bool)
    unique[1:] = stamps[1:] != stamps[:-1]
    stamps, values = stamps[unique], values[unique]

    start = stamps[0] - stamps[0] % _HOUR_NS
    last = stamps[-1] - stamps[-1] % _HOUR_NS
    if (last - start) // _HOUR_NS + 1 < n_steps:
        return None

    offset = stamps - start
    on_grid = (offset % _HOUR_NS == 0) & (offset < n_steps * _HOUR_NS)
    out = np.full(n_steps, np.nan)
    out[(offset[on_grid] // _HOUR_NS).astype(np.int64)] = values[on_grid]
    return out


def build_signal_channels(
    vitals: pd.DataFrame,
    chemistry: pd.DataFrame,
    stay_ids: np.ndarray,
    n_steps: int = N_STEPS,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Value + missingness channels for the eight signals, over the first 72 hours.

    A stay is dropped when any signal it does have spans fewer than ``n_steps``
    hours.  A lab the subject never had is kept as an all-missing channel pair.
    Vitals are looked up by stay, labs by subject, as in the reference.
    """
    vitals = vitals[vitals["stay_id"].isin(stay_ids)]
    stay_to_subject = (
        vitals.drop_duplicates("stay_id").set_index("stay_id")["subject_id"].to_dict()
    )
    vital_groups = dict(tuple(vitals.groupby("stay_id", sort=False)))
    subjects = set(stay_to_subject.values())
    chem_groups = dict(
        tuple(chemistry[chemistry["subject_id"].isin(subjects)].groupby("subject_id", sort=False))
    )

    kept_stays: list[int] = []
    kept_subjects: list[int] = []
    rows: list[np.ndarray] = []
    for n, stay_id in enumerate(stay_ids):
        if n and n % 2000 == 0:
            LOG.info("  channels %s / %s", f"{n:,}", f"{len(stay_ids):,}")
        subject_id = stay_to_subject[stay_id]
        stay_frame = vital_groups[stay_id]
        subject_frame = chem_groups.get(subject_id)

        channels: list[np.ndarray] = []
        for name in SIGNALS:
            is_lab = name in LAB_ITEMS
            frame = subject_frame if is_lab else stay_frame
            if frame is None or frame[name].notna().sum() == 0:
                if not is_lab:
                    channels = []
                    break
                series = np.full(n_steps, np.nan)
            else:
                observed = frame[[name]].dropna()
                series = _hourly_window(
                    pd.DatetimeIndex(frame.loc[observed.index, "charttime"]),
                    observed[name].to_numpy(),
                    round_to="20min" if is_lab else None,
                    n_steps=n_steps,
                )
                if series is None:
                    channels = []
                    break
            channels.append(series)
            channels.append(np.isnan(series).astype("float64"))

        if len(channels) != 2 * len(SIGNALS):
            continue
        rows.append(np.stack(channels))
        kept_stays.append(int(stay_id))
        kept_subjects.append(int(subject_id))

    if not rows:
        empty = np.empty((0, 2 * len(SIGNALS), n_steps), dtype="float32")
        return empty, np.empty(0, dtype="int64"), np.empty(0, dtype="int64")
    LOG.info("build_signal_channels: %s of %s stays kept", f"{len(rows):,}", f"{len(stay_ids):,}")
    return (
        np.stack(rows).astype("float32"),
        np.asarray(kept_stays, dtype="int64"),
        np.asarray(kept_subjects, dtype="int64"),
    )


def load_top_icd(csv_dir: Path, n_codes: int = N_STEPS) -> pd.DataFrame:
    """Binary subject x top-``n_codes`` ICD table.

    ``mimic4_save_icd.py`` ranks codes by how often they are coded and orders the
    matrix columns by that rank; the tensor then slices the first 72 columns.
    """
    path = csv_dir / "hosp" / "diagnoses_icd.csv"
    LOG.info("icd: reading %s", path)
    icd = pd.read_csv(path, usecols=["subject_id", "icd_code"], dtype={"subject_id": "int64", "icd_code": "string"})
    top = icd["icd_code"].value_counts().index[:n_codes]
    icd = icd[icd["icd_code"].isin(set(top))].drop_duplicates()
    rank = {code: i for i, code in enumerate(top)}
    table = np.zeros((icd["subject_id"].nunique(), n_codes), dtype="float32")
    subject_index = {s: i for i, s in enumerate(icd["subject_id"].unique())}
    table[
        icd["subject_id"].map(subject_index).to_numpy(),
        icd["icd_code"].map(rank).to_numpy(),
    ] = 1.0
    LOG.info("icd: top %s codes over %s subjects", n_codes, f"{len(subject_index):,}")
    return pd.DataFrame(table, index=pd.Index(list(subject_index), name="subject_id"))


def load_top_antibiotics(
    csv_dir: Path, n_drugs: int = N_STEPS, chunksize: int = 2_000_000
) -> pd.DataFrame:
    """Binary subject x top-``n_drugs`` antibiotic table.

    ``mimiciv_derived.antibiotic`` is rebuilt with the drug-name and route rules
    from concepts/medication/antibiotic.sql; drugs are then ranked by how many
    subjects received them, as in the reference.
    """
    path = csv_dir / "hosp" / "prescriptions.csv"
    LOG.info("antibiotic: scanning %s", path)
    pairs: list[pd.DataFrame] = []
    for chunk in _read_chunks(
        path,
        usecols=["subject_id", "drug", "drug_type", "route"],
        dtype={"subject_id": "int64", "drug": "string", "drug_type": "string", "route": "string"},
        chunksize=chunksize,
    ):
        chunk = chunk[chunk["drug"].notna() & chunk["route"].notna()]
        chunk = chunk[chunk["drug_type"] != "BASE"]
        route = chunk["route"].str.lower()
        chunk = chunk[
            ~chunk["route"].isin(_EXCLUDED_ROUTES)
            & ~route.str.contains("ear", na=False)
            & ~route.str.contains("eye", na=False)
        ]
        drug = chunk["drug"].str.lower()
        chunk = chunk[
            ~drug.str.contains("cream", na=False)
            & ~drug.str.contains("desensitization", na=False)
            & ~drug.str.contains("ophth oint", na=False)
            & ~drug.str.contains("gel", na=False)
        ]
        if chunk.empty:
            continue
        drug = chunk["drug"].str.lower()
        keep = drug.str.contains(_ANTIBIOTIC_PATTERN, regex=True, na=False)
        if not keep.any():
            continue
        pairs.append(chunk.loc[keep, ["subject_id", "drug"]].drop_duplicates())

    if not pairs:
        return pd.DataFrame(np.zeros((0, n_drugs), dtype="float32"), index=pd.Index([], name="subject_id"))
    abx = pd.concat(pairs, ignore_index=True).drop_duplicates()
    top = abx["drug"].value_counts().index[:n_drugs]
    abx = abx[abx["drug"].isin(set(top))]
    rank = {drug: i for i, drug in enumerate(top)}
    subject_index = {s: i for i, s in enumerate(abx["subject_id"].unique())}
    table = np.zeros((len(subject_index), n_drugs), dtype="float32")
    table[
        abx["subject_id"].map(subject_index).to_numpy(),
        abx["drug"].map(rank).to_numpy(),
    ] = 1.0
    LOG.info("antibiotic: top %s drugs over %s subjects", n_drugs, f"{len(subject_index):,}")
    return pd.DataFrame(table, index=pd.Index(list(subject_index), name="subject_id"))


def load_static(csv_dir: Path) -> tuple[pd.Series, set[int]]:
    """``anchor_age`` per subject and the subjects who died in hospital."""
    patients = pd.read_csv(
        csv_dir / "hosp" / "patients.csv",
        usecols=["subject_id", "anchor_age"],
        dtype={"subject_id": "int64", "anchor_age": "float32"},
    )
    age = patients.drop_duplicates("subject_id").set_index("subject_id")["anchor_age"]
    admissions = pd.read_csv(
        csv_dir / "hosp" / "admissions.csv",
        usecols=["subject_id", "hospital_expire_flag"],
        dtype={"subject_id": "int64", "hospital_expire_flag": "float32"},
    )
    expired = set(admissions.loc[admissions["hospital_expire_flag"] == 1, "subject_id"])
    LOG.info("static: %s subjects with age, %s expired", f"{len(age):,}", f"{len(expired):,}")
    return age, expired


def add_static_channels(
    signals: np.ndarray,
    subject_ids: np.ndarray,
    icd: pd.DataFrame,
    antibiotics: pd.DataFrame,
    age: pd.Series,
    expired: set[int],
) -> np.ndarray:
    """Append the four channels that are constant over the 72 hours."""
    n, _, n_steps = signals.shape
    icd_rows = icd.reindex(subject_ids).fillna(0.0).to_numpy(dtype="float32")
    abx_rows = antibiotics.reindex(subject_ids).fillna(0.0).to_numpy(dtype="float32")
    age_rows = np.repeat(
        age.reindex(subject_ids).fillna(0.0).to_numpy(dtype="float32")[:, None], n_steps, axis=1
    )
    mort_rows = np.repeat(
        np.isin(subject_ids, list(expired)).astype("float32")[:, None], n_steps, axis=1
    )
    statics = np.stack([icd_rows, abx_rows, age_rows, mort_rows], axis=1)
    LOG.info("add_static_channels: mortality rate %.3f", mort_rows[:, 0].mean() if n else 0.0)
    return np.concatenate([signals, statics], axis=1)


def split_train_test(
    tensor: np.ndarray, stay_ids: np.ndarray, seed: int = 2023, train_frac: float = 0.75
) -> dict[str, np.ndarray]:
    """75/25 split stratified on the mortality channel, as in the reference.

    The reference defers to ``sklearn.train_test_split``; this is an equivalent
    numpy implementation so the module needs no scikit-learn, and the assignment
    of individual stays therefore differs from the reference run.
    """
    rng = np.random.default_rng(seed)
    order = rng.permutation(len(tensor))
    tensor, stay_ids = tensor[order], stay_ids[order]

    labels = tensor[:, -1, 0]
    n_test = len(tensor) - int(len(tensor) * train_frac)
    classes, counts = np.unique(labels, return_counts=True)
    quota = counts * n_test / len(tensor)
    per_class = np.floor(quota).astype(int)
    short = n_test - per_class.sum()
    if short > 0:
        for i in np.argsort(-(quota - per_class))[:short]:
            per_class[i] += 1

    test_idx: list[np.ndarray] = []
    for label, take in zip(classes, per_class):
        members = np.flatnonzero(labels == label)
        test_idx.append(rng.permutation(members)[:take])
    test_mask = np.zeros(len(tensor), dtype=bool)
    test_mask[np.concatenate(test_idx)] = True

    return {
        "train": tensor[~test_mask],
        "test": tensor[test_mask],
        "stays_train": stay_ids[~test_mask],
        "stays_test": stay_ids[test_mask],
    }


def channel_names() -> list[str]:
    names = [f"{s}{suffix}" for s in SIGNALS for suffix in ("", "_mask")]
    return names + list(STATIC_CHANNELS)


# every annotation emitted per stay, with the description written into the json
ANNOTATION_FIELDS: dict[str, str] = {
    "split": "train or test, matching which tensor the stay was saved in",
    "subject_id": "MIMIC-IV patient identifier",
    "hadm_id": "hospital admission the ICU stay belongs to",
    "gender": "patients.gender",
    "age": "patients.anchor_age, the age at the anchor year (also tensor channel 19)",
    "admission_type": "admissions.admission_type, e.g. EW EMER. / ELECTIVE / OBSERVATION",
    "admission_location": "admissions.admission_location",
    "insurance": "admissions.insurance",
    "marital_status": "admissions.marital_status",
    "race": "admissions.race",
    "via_ed": "1 when admissions.edregtime is set, i.e. the patient came through the ED",
    "first_careunit": "icustays.first_careunit",
    "last_careunit": "icustays.last_careunit",
    "icu_stay_number": "1-based rank of this ICU stay among the subject's stays, by intime",
    "los_icu_days": "icustays.los",
    "los_hospital_days": "dischtime - admittime, in days",
    "discharge_location": "admissions.discharge_location; DIED and HOSPICE are outcomes too",
    "mortality_in_hospital": (
        "admissions.hospital_expire_flag for the admission this ICU stay belongs to."
        " Tensor channel 20 is NOT the same label: following the reference it marks any"
        " subject who died in any of their admissions, so it is 1 for some stays where"
        " this field is 0. Prefer this one"
    ),
    "mortality_in_icu": "1 when admissions.deathtime falls inside the ICU intime..outtime window",
    "days_discharge_to_death": (
        "patients.dod minus dischtime, in days; null when no date of death is known."
        " Zero or negative for an in-hospital death, since dod is only a date"
    ),
    "mortality_30day": "1 when dod is known and falls no later than 30 days after discharge",
    "mortality_1year": "1 when dod is known and falls no later than 365 days after discharge",
    "readmission_30day": (
        "1 when the subject is admitted again within 30 days of this discharge;"
        " 0 for patients who died in hospital, as they cannot be readmitted"
    ),
    "primary_icd_code": "icd_code at the lowest seq_num of the admission",
    "primary_icd_version": "9 or 10",
    "primary_icd_title": "d_icd_diagnoses.long_title of the primary code",
    "icd_codes": "every icd_code billed for the admission, ordered by seq_num",
    "icd_version": "the admission's coding system, or null for the rare mixed admission",
    "drg_description": "APR-DRG description from drgcodes.csv",
    "drg_severity": "APR-DRG severity of illness, 1-4",
    "drg_mortality": "APR-DRG risk of mortality, 1-4",
    "services": "curr_service values of the admission, ordered by transfertime",
    "first_service": "the admission's first curr_service, e.g. MED / SURG / CMED",
}

_BINARY_LABELS = (
    "mortality_in_hospital",
    "mortality_in_icu",
    "mortality_30day",
    "mortality_1year",
    "readmission_30day",
    "via_ed",
)


def _json_safe(value):
    """numpy scalars, pandas NA and NaN are not json-serialisable as they are."""
    if isinstance(value, (list, tuple)):
        return [_json_safe(v) for v in value]
    if value is None or value is pd.NA or value is pd.NaT:
        return None
    if isinstance(value, str):
        return value
    if isinstance(value, (bool, np.bool_)):  # before int, bool subclasses it
        return int(value)
    if isinstance(value, (int, np.integer)):
        return int(value)
    if isinstance(value, (float, np.floating)):
        return None if np.isnan(value) else float(value)
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass
    return str(value)


def load_annotations(csv_dir: Path, splits: dict[str, np.ndarray]) -> dict:
    """Per-stay status labels for the saved cohort, keyed by ``stay_id``.

    None of this is used by the tensors; it is the outcome and diagnosis
    metadata the CSV release carries, collected so the saved stays can be
    conditioned on or evaluated against something richer than the single
    in-hospital mortality bit that occupies tensor channel 20.
    """
    stay_ids = np.concatenate([splits["stays_train"], splits["stays_test"]])
    split_of = {int(s): "train" for s in splits["stays_train"]}
    split_of.update({int(s): "test" for s in splits["stays_test"]})
    LOG.info("annotations: collecting for %s stays", f"{len(stay_ids):,}")

    icu = pd.read_csv(
        csv_dir / "icu" / "icustays.csv",
        usecols=["subject_id", "hadm_id", "stay_id", "first_careunit", "last_careunit", "intime", "outtime", "los"],
    )
    icu["intime"] = _to_datetime(icu["intime"])
    icu["outtime"] = _to_datetime(icu["outtime"])
    icu["icu_stay_number"] = (
        icu.sort_values("intime").groupby("subject_id").cumcount().add(1).reindex(icu.index)
    )
    icu = icu[icu["stay_id"].isin(set(int(s) for s in stay_ids))].set_index("stay_id")

    adm = pd.read_csv(
        csv_dir / "hosp" / "admissions.csv",
        usecols=[
            "subject_id", "hadm_id", "admittime", "dischtime", "deathtime", "admission_type",
            "admission_location", "discharge_location", "insurance", "marital_status", "race",
            "edregtime", "hospital_expire_flag",
        ],
    )
    for col in ("admittime", "dischtime", "deathtime"):
        adm[col] = _to_datetime(adm[col])
    # a readmission is the subject's next admission, so this needs every row
    ordered = adm.sort_values(["subject_id", "admittime"])
    gap = (
        ordered.groupby("subject_id")["admittime"].shift(-1) - ordered["dischtime"]
    ).dt.total_seconds() / 86400.0
    adm["readmit_gap_days"] = gap.reindex(adm.index)
    adm = adm.set_index("hadm_id")

    patients = pd.read_csv(csv_dir / "hosp" / "patients.csv", usecols=["subject_id", "gender", "anchor_age", "dod"])
    patients["dod"] = pd.to_datetime(patients["dod"], format="%Y-%m-%d", errors="coerce")
    patients = patients.drop_duplicates("subject_id").set_index("subject_id")

    hadm_ids = set(icu["hadm_id"].dropna().astype("int64"))
    dx = pd.read_csv(
        csv_dir / "hosp" / "diagnoses_icd.csv",
        usecols=["hadm_id", "seq_num", "icd_code", "icd_version"],
    )
    dx = dx[dx["hadm_id"].isin(hadm_ids)].sort_values(["hadm_id", "seq_num"], kind="stable")
    titles = pd.read_csv(csv_dir / "hosp" / "d_icd_diagnoses.csv", usecols=["icd_code", "icd_version", "long_title"])
    title_of = {
        (code, version): title
        for code, version, title in titles.itertuples(index=False, name=None)
    }
    codes_of = dx.groupby("hadm_id")["icd_code"].apply(list).to_dict()
    # seq_num 1 is not unique for a handful of admissions, so take the first row
    primary = dx.drop_duplicates("hadm_id").set_index("hadm_id")
    versions = dx.groupby("hadm_id")["icd_version"].nunique()

    drg = pd.read_csv(
        csv_dir / "hosp" / "drgcodes.csv",
        usecols=["hadm_id", "drg_type", "description", "drg_severity", "drg_mortality"],
    )
    drg = drg[(drg["drg_type"] == "APR") & drg["hadm_id"].isin(hadm_ids)]
    drg = drg.drop_duplicates("hadm_id").set_index("hadm_id")

    svc = pd.read_csv(csv_dir / "hosp" / "services.csv", usecols=["hadm_id", "transfertime", "curr_service"])
    svc = svc[svc["hadm_id"].isin(hadm_ids)]
    svc["transfertime"] = _to_datetime(svc["transfertime"])
    services_of = (
        svc.sort_values("transfertime", kind="stable").groupby("hadm_id")["curr_service"].apply(list).to_dict()
    )

    records: dict[str, dict] = {}
    for stay_id in stay_ids:
        stay_id = int(stay_id)
        if stay_id not in icu.index:
            continue
        stay = icu.loc[stay_id]
        hadm_id = stay["hadm_id"]
        subject_id = int(stay["subject_id"])
        admission = adm.loc[hadm_id] if hadm_id in adm.index else None
        person = patients.loc[subject_id] if subject_id in patients.index else None

        died_in_hospital = int(admission["hospital_expire_flag"]) if admission is not None else 0
        deathtime = admission["deathtime"] if admission is not None else pd.NaT
        dischtime = admission["dischtime"] if admission is not None else pd.NaT
        dod = person["dod"] if person is not None else pd.NaT

        to_death = (
            (dod - dischtime).total_seconds() / 86400.0
            if not pd.isna(dod) and not pd.isna(dischtime)
            else None
        )
        gap_days = admission["readmit_gap_days"] if admission is not None else np.nan
        diagnoses = codes_of.get(hadm_id, [])
        row = primary.loc[hadm_id] if hadm_id in primary.index else None
        drg_row = drg.loc[hadm_id] if hadm_id in drg.index else None

        record = {
            "split": split_of[stay_id],
            "subject_id": subject_id,
            "hadm_id": int(hadm_id) if not pd.isna(hadm_id) else None,
            "gender": person["gender"] if person is not None else None,
            "age": person["anchor_age"] if person is not None else None,
            "admission_type": admission["admission_type"] if admission is not None else None,
            "admission_location": admission["admission_location"] if admission is not None else None,
            "insurance": admission["insurance"] if admission is not None else None,
            "marital_status": admission["marital_status"] if admission is not None else None,
            "race": admission["race"] if admission is not None else None,
            "via_ed": int(admission is not None and not pd.isna(admission["edregtime"])),
            "first_careunit": stay["first_careunit"],
            "last_careunit": stay["last_careunit"],
            "icu_stay_number": stay["icu_stay_number"],
            "los_icu_days": stay["los"],
            "los_hospital_days": (
                (dischtime - admission["admittime"]).total_seconds() / 86400.0
                if admission is not None and not pd.isna(dischtime) and not pd.isna(admission["admittime"])
                else None
            ),
            "discharge_location": admission["discharge_location"] if admission is not None else None,
            "mortality_in_hospital": died_in_hospital,
            "mortality_in_icu": int(
                not pd.isna(deathtime)
                and not pd.isna(stay["intime"])
                and stay["intime"] <= deathtime <= stay["outtime"]
            ),
            "days_discharge_to_death": to_death,
            "mortality_30day": int(to_death is not None and to_death <= 30),
            "mortality_1year": int(to_death is not None and to_death <= 365),
            "readmission_30day": int(
                not died_in_hospital and not pd.isna(gap_days) and 0 <= gap_days <= 30
            ),
            "primary_icd_code": row["icd_code"] if row is not None else None,
            "primary_icd_version": row["icd_version"] if row is not None else None,
            "primary_icd_title": (
                title_of.get((row["icd_code"], row["icd_version"])) if row is not None else None
            ),
            "icd_codes": diagnoses,
            "icd_version": (
                row["icd_version"] if row is not None and versions.get(hadm_id, 0) == 1 else None
            ),
            "drg_description": drg_row["description"] if drg_row is not None else None,
            "drg_severity": drg_row["drg_severity"] if drg_row is not None else None,
            "drg_mortality": drg_row["drg_mortality"] if drg_row is not None else None,
            "services": services_of.get(hadm_id, []),
            "first_service": (services_of.get(hadm_id) or [None])[0],
        }
        records[str(stay_id)] = {k: _json_safe(v) for k, v in record.items()}

    summary = {}
    for label in _BINARY_LABELS:
        values = [r[label] for r in records.values() if r[label] is not None]
        if values:
            summary[label] = {
                "positive": int(sum(values)),
                "rate": round(sum(values) / len(values), 4),
            }
    missing = len(stay_ids) - len(records)
    if missing:
        LOG.warning("annotations: %s stays absent from icustays.csv", missing)
    for label, stats in summary.items():
        LOG.info("  %-22s %6d  %.3f", label, stats["positive"], stats["rate"])

    return {
        "description": (
            "Per-ICU-stay status annotations for the cohort saved in train.npy / test.npy,"
            " keyed by stay_id. Independent of the tensors: nothing here is a model input"
            " unless you make it one."
        ),
        "source": "MIMIC-IV 3.1 hosp/ and icu/ CSVs",
        "n_stays": len(records),
        "label_rates": summary,
        "fields": ANNOTATION_FIELDS,
        "stays": records,
    }


def preprocess(
    csv_dir: Path,
    out_dir: Path,
    min_measurements: int = 70,
    chunksize: int = 2_000_000,
    nrows: int | None = None,
    seed: int = 2023,
) -> dict[str, Path]:
    vitals = load_vitalsign(csv_dir, chunksize=chunksize, nrows=nrows)
    if vitals.empty:
        raise RuntimeError(f"no vital signs found under {csv_dir}")
    chemistry = load_chemistry(csv_dir, chunksize=max(chunksize, 2_000_000), nrows=nrows)
    stay_ids = select_stays(vitals, min_measurements=min_measurements)
    if len(stay_ids) == 0:
        raise RuntimeError("no ICU stay met the vital-sign count threshold")

    signals, stays, subjects = build_signal_channels(vitals, chemistry, stay_ids)
    if len(stays) == 0:
        raise RuntimeError("no ICU stay had 72 hours of every observed signal")
    del vitals, chemistry

    icd = load_top_icd(csv_dir)
    antibiotics = load_top_antibiotics(csv_dir, chunksize=chunksize)
    age, expired = load_static(csv_dir)
    tensor = add_static_channels(signals, subjects, icd, antibiotics, age, expired)
    LOG.info("tensor: %s", tensor.shape)

    parts = split_train_test(tensor, stays, seed=seed)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for name, array in parts.items():
        path = out_dir / f"{name}.npy"
        np.save(path, array)
        written[name] = path
        LOG.info("wrote %s %s", path, array.shape)

    meta = out_dir / "channels.json"
    meta.write_text(
        json.dumps(
            {
                "source": "MIMIC-IV CSV, preprocessing translated from TimeDiff mimic4_everything.ipynb",
                "n_steps": N_STEPS,
                "granularity": "1 hour",
                "channels": channel_names(),
                "n_train": int(len(parts["train"])),
                "n_test": int(len(parts["test"])),
                "min_measurements_per_vital": min_measurements,
            },
            indent=2,
        )
    )
    written["channels"] = meta

    annotations = out_dir / "annotations.json"
    annotations.write_text(json.dumps(load_annotations(csv_dir, parts), indent=2))
    written["annotations"] = annotations
    LOG.info("wrote %s", annotations)
    return written


_MIMIC_SUBPATH = Path("physionet.org/files/mimiciv/3.1")


def _default_csv_dir() -> Path:
    """First place the download is actually sitting, else the in-repo location."""
    repo_root = Path(__file__).resolve().parents[1]
    candidates = (repo_root / _MIMIC_SUBPATH, Path.home() / "Desktop" / _MIMIC_SUBPATH)
    for candidate in candidates:
        if (candidate / "icu" / "chartevents.csv").exists():
            return candidate
    return candidates[0]


def build_parser() -> argparse.ArgumentParser:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="MIMIC-IV CSV -> hourly ICU tensors, following TimeDiff's preprocessing."
    )
    parser.add_argument(
        "--csv-dir",
        type=Path,
        default=_default_csv_dir(),
        help="directory holding the MIMIC-IV hosp/ and icu/ CSVs",
    )
    parser.add_argument("--out-dir", type=Path, default=repo_root / "processed_mimic")
    parser.add_argument("--min-measurements", type=int, default=70)
    parser.add_argument("--chunksize", type=int, default=2_000_000)
    parser.add_argument(
        "--nrows",
        type=int,
        default=None,
        help="cap rows read from chartevents/labevents for a smoke test",
    )
    parser.add_argument("--seed", type=int, default=2023)
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    args = build_parser().parse_args(argv)
    preprocess(
        csv_dir=args.csv_dir,
        out_dir=args.out_dir,
        min_measurements=args.min_measurements,
        chunksize=args.chunksize,
        nrows=args.nrows,
        seed=args.seed,
    )


if __name__ == "__main__":
    main()
